### ISSUE TITLE
additional times to workflow - EJP data dump every 2 hours

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-poa-xml-generation#201]

**Comment by gnott** [comment]
Initial plans

* What time of the day to run, whether during work hours only, or around the clock (if errors are encountered they can be remedied later)

* Schedule for new time windows: This looks simple in the current configuration. The bucket receiving input is polled each hour already. When PackagePOA runs, it finds all objects that were modified since the last time PackagePOA was run. Currently that is 24 hours, and in adding additional run times it will use the previous run time as its time period to discover new files

* Change batch file names to include the hour executued, e.g. ``elife_poa_20150507.zip``  would become ``elife_poa_20150507-11.zip``. This file name must be unique for each delivery

**Comment by Melissa37** [comment]
Have requested EJP to add time stamp to CSV export.

**Comment by Melissa37** [comment]
From EJP: Apologies again for the delay. After taking a further look, unfortunately it does not appear that the file name format is currently configurable. I would be happy to submit a request with our Developers to explore the level of effort to make this change and wanted to confirm the desired formatting. Could you please let me know formatting of the time stamp that you would like displayed?

**Comment by Melissa37** [comment]
Closed, on JIRA: http://jira.elifesciences.org:8080/browse/ELPP-922
